"""initial baseline

Revision ID: d2772175c1e4
Revises: 
Create Date: 2026-05-21 23:24:28.409926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2772175c1e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_pinyin_search'), ['pinyin_search'], unique=False)

    with op.batch_alter_table('quote_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_items_quote_id'), ['quote_id'], unique=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_quotes_created_by'))

    with op.batch_alter_table('quote_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_items_quote_id'))
        batch_op.drop_index(batch_op.f('ix_quote_items_product_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_pinyin_search'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))

    # ### end Alembic commands ###
