"""v2.6.0: product advanced features - dicts, categories, M2M mappings, product extensions

Revision ID: e0d0ca6f2b58
Revises: d2772175c1e4
Create Date: 2026-05-28 22:17:24.033725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d0ca6f2b58'
down_revision = 'd2772175c1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_products_manufacturer_id', 'manufacturers', ['manufacturer_id'], ['id'])
        batch_op.create_foreign_key('fk_products_supplier_id', 'suppliers', ['supplier_id'], ['id'])
        batch_op.create_foreign_key('fk_products_category_id', 'device_categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_products_parent_id', 'products', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_manufacturer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_products_supplier_id', type_='foreignkey')
        batch_op.drop_constraint('fk_products_category_id', type_='foreignkey')
        batch_op.drop_constraint('fk_products_parent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_parent_id'))
        batch_op.drop_index(batch_op.f('ix_products_model'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    # ### end Alembic commands ###
